apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-k8s-app
  template:
    metadata:
      labels:
        app: go-k8s-app
    spec:
      containers:
        - name: go-k8s-container
          image: go-k8s-cicd-example:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
      # Adicione esta seção caso precise de autenticação no registry
      # imagePullSecrets:
      # - name: my-registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: go-k8s-service
spec:
  type: NodePort
  selector:
    app: go-k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000  # Certifique-se de que esta porta não conflite com outras portas
