apiVersion: v1
kind: Service
metadata:
  name: go-k8s-service
spec:
  type: NodePort
  selector:
    app: go-k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000  # A porta externa que você vai acessar com curl
