apiVersion: v1
kind: Service
metadata:
  name: go-k8s-app
spec:
  selector:
    app: go-k8s-app
  ports:
    - protocol: TCP
      port: 80          # Porta exposta externamente
      targetPort: 8080  # Porta do Pod
      nodePort: 31374   # Porta externa acessível
  type: NodePort
