name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Isso garante que o workflow será acionado quando houver um push para a branch main
  pull_request:
    branches:
      - main  # Isso pode ser usado para rodar o CI também em PRs para a branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t your-username/go-k8s-cicd-example:latest .
        docker push your-username/go-k8s-cicd-example:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        export KUBECONFIG=kubeconfig

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/go-k8s-app go-k8s-app=your-username/go-k8s-cicd-example:latest
        kubectl rollout status deployment/go-k8s-app
